% FILEPATH: /Users/shaanyadav/Desktop/Duke Courses/ECE 280/Lab 5 - Image Processing/example1.m
% This code creates a matrix 'a' and displays it as an image using the 'imagesc' function.
% The matrix 'a' represents a binary image with 1s and 0s.
% The resulting image is displayed in grayscale with a colorbar.
a = [ 1 0 1 0 0; ...
    1 0 1 0 1; ...
    1 1 1 0 0; ...
    1 0 1 0 1; ...
    1 0 1 0 1 ];
figure(1); clf
imagesc(a)
colormap gray; colorbar
